services:
  db:
    image: postgres:15-alpine
    container_name: atis-postgres-dev
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME:-atis_db}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-your_secure_password}
    volumes:
      - postgres_atis_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: atis-next-dev
    env_file:
      - .env
    command: npm run dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - db

  atis-adminer:
    image: adminer
    container_name: atis-adminer
    environment:
      ADMINER_DEFAULT_SERVER: db
    ports:
      - "9090:8080"

volumes:
  postgres_atis_data:
